### ISSUE TITLE
Sample Config And Documetation

### ISSUE THREAD

**Issue by billyprice1old** [lizardlab/bluebase#1]
Hi this looks like a cool project i got the server connecting but i wish there was some openvpn docs and a sample config please thanks im haveing issues

**Comment by lizardlab** [comment]
Please take a look at my other project openvpn-tutorials which has my personal write-up of creating a new OpenVPN server, I saw you already forked it. I derived those instructions from the [Archwiki](https://wiki.archlinux.org/index.php/OpenVPN) and Debian [Wiki](https://wiki.debian.org/OpenVPN) (very helpful). There are also various tutorials on how to setup OpenVPN especially for the Raspberry Pi (which can easily be used on a debian server) or like this [one](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-14-04) on digital ocean (so you don't need to have a server in your actual place). Have fun!
