### ISSUE TITLE
failed running command (--auth-user-pass-verify)

### ISSUE THREAD

**Issue by jomsky10** [lizardlab/bluebase#2]
this is an openvpn logs which if the user attempt to connect it returns an error failed running command (--auth-user-pass-verify) external program exited with an error status: 1

**Comment by lizardlab** [comment]
please ensure that your database is working correctly and also that you have installed all the libraries and set the executable bit on the python file.

**Comment by jomsky10** [comment]
error log of my server.conf

![image](https://cloud.githubusercontent.com/assets/9735474/21953057/9e800a10-da68-11e6-959b-595b97259c77.png)

**Comment by lizardlab** [comment]
Please try python 2.7
