### ISSUE TITLE
Some Modifications

### ISSUE THREAD

**Issue by jomsky10** [lizardlab/bluebase#3]
hi, I have some request or can you give some specific instruction to change some of its features since I'm not knowledgable at PHP but I can to some edits.

1. how to hide the ID number and pie chart in dashboard? 
2. how to rename the value of Expiration status from NULL to other name/strings? and also the Disabled status how to rename the True/False to other strings?
3.  can you add some search box for usernames or sort on specific fields.
4. please add a notifier if a user is added :)

thanks.. your work is great.

**Comment by lizardlab** [comment]
Hello, well this is just a side project and personally I have it setup in a way I find pleasing so I am not going to change the aesthetics of it, but most of the changes you want can be done in the HTML and Javascript without affecting the backend code. The PHP files themselves have the HTML embedded within them.
1. Look at [dashboard.php](https://github.com/lizardlab/bluebase/blob/master/frontend/dashboard.php#L114-L116) and [bluebase.js](https://github.com/lizardlab/bluebase/blob/master/frontend/js/bluebase.js#L211-L242) to change the table stuff
2. Look at the table creation [code](https://github.com/lizardlab/bluebase/blob/master/frontend/js/bluebase.js#L224-L231) in bluebase.js to see what you want to change
3. This was an idea I was having, but I currently can't get to, I have a busy schedule. But in the future it might be added.
4. Administrators are the only people that can add users, users cannot self-register only change their passwords. If you want to be notified if another administrator adds a user I'm not sure how to go about doing that, but at this time I do not feel like it's a feature worth adding to the project.

**Comment by jomsky10** [comment]
thanks for your reply.

1.  I can't get to work to hide the User ID column on dashboard.php if I comment out the "User ID"  table header the table adjust but the data don't. 

![image](https://cloud.githubusercontent.com/assets/9735474/22605400/a57c5422-ea8a-11e6-9f9e-ec92c63fc2f4.png)

2. also I can't find the "Null" string in Expiration table header. 

![image](https://cloud.githubusercontent.com/assets/9735474/22605500/1216164a-ea8b-11e6-99ec-14848c01b1ad.png)

I did change on some strings that denotes True/False to make it  Enabled/Disabled  in exchange of True/False value on "Disabled" table header but no luck.. am I missing something?

![image](https://cloud.githubusercontent.com/assets/9735474/22605603/8a396d34-ea8b-11e6-8b7d-f82ddbe27e5f.png)

Sorry for being noob... I wish I have knowledge on hardcore programming... not to mention I'm not that familiar with javascript :(

**Comment by jomsky10** [comment]
up
