### ISSUE TITLE
Database table name

### ISSUE THREAD

**Issue by jomsky10** [lizardlab/bluebase#4]
Hi @lizardlab, I want to rename the database table "hash_pass" to "password" for some reason I know it will affect the auth.py because it contains some codes that needs the hash_pass table name... can you assist me with this?

**Comment by lizardlab** [comment]
Hello,
The hash_pass is a database column in the users table, not a table itself. Also if you are to look, you'd need to change it in at least [4 places](https://github.com/lizardlab/bluebase/search?utf8=%E2%9C%93&q=hashed_pass), just seems like a lot of work for a little variable name. Please do not put in issues for small trivial requests such as these, they take too much time with not much payout. I purposefully named it hashed_pass to ensure people know its a Bcrypt hashed password, so it can't be handled as plaintext. You are free to change what you wish as per the GPLv3, but I have many other things to attend to and do not really see the importance of changing a column name. If this is for a business project, I suggest hiring a software developer competent in PHP and some basic Python. If you are really just a beginner I suggest checking out various online resources which can help you learn about programming, such as [Codeacademy](https://www.codecademy.com/), [Coursera](https://www.coursera.org/browse/computer-science?languages=en), [edX](https://www.edx.org/course/subject/computer-science), and many [others](http://web.archive.org/web/20170301141803/http://noexcuselist.com/). I have recently been very busy and this is my first vacation in a while for spring break, so I can finally get back to programming. However I want to create new projects, not change superficial details on old ones, please be mindful of that. Best of luck on your programming endeavors.

**Comment by jomsky10** [comment]
thanks for encouraging words.. I'll keep that in mind. :)
